theme: jekyll-theme-minimal
markdown: GFM
title: IRTG Course
description: <h3>Introduction to R for genomics</h3>  <figure><img src="./TRR179.png"></figure><h4>Carl Herrmann & Carlos Ramirez</h4>16-17 June 2021 